pipeline{
    agent any
    tools{
        maven "maven"

    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/cvstleee/TINGESO_APPWEB']])
                dir("trabajo-tingeso/backend/tingeso"){
                    bat "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("trabajo-tingeso/backend/tingeso"){
                    bat "mvn test"
                }
            }
        }        
        stage("Build and Push Docker Image"){
            steps{
                dir("trabajo-tingeso/backend/tingeso"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t cvstleee/tingesobackend ."
                            bat "docker push cvstleee/tingesobackend"
                        }
                    }                    
                }
            }
        }
    }
}
