version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: nginxbackendcontainer
    restart: always
    ports:
      - 8090:8090
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network
    depends_on:
      - spring1
      - spring2
      - spring3      
  nginx-frontend:
    image: nginx
    container_name: nginxfrontendcontainer
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    networks:
      - frontend-network
    depends_on:      
      - react1
      - react2
      - react3
  postgres:
    container_name: postgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - pg-volume:/var/lib/postgresql/data -d postgres
    networks:
      - backend-network
    environment:      
      POSTGRES_DB: prestabancodb
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432      
  spring1:
    container_name: backend-container-1
    image: cvstleee/tingesobackend
    ports:
      - 8091:8090
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/prestabancodb
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring2:
    container_name: backend-container-2
    image: cvstleee/tingesobackend
    ports:
      - 8092:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/prestabancodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring3:
    container_name: backend-container-3
    image: cvstleee/tingesobackend
    ports:
      - 8093:8090
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/prestabancodb
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - backend-network
    deploy:
      restart_policy:
        condition: on-failure
  react1:
    container_name: frontend-container-1
    image: cvstleee/tingesofrontend
    ports:
      - 3001:80
    networks:
      - frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: frontend-container-2
    image: cvstleee/tingesofrontend
    ports:
      - 3002:80
    networks:
      - frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: frontend-container-3
    image: cvstleee/tingesofrontend
    networks:
      - frontend-network
    ports:
      - 3003:80
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  pg-volume:
networks:
  frontend-network:
  backend-network: