pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/cvstleee/TINGESO_APPWEB']])
                dir("trabajo-tingeso/frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("trabajo-tingeso/frontend"){
                    script{
                        withCredentials([string(credentialsId: 'cvstleee', variable: 'Aylin406#')]) {
                        bat 'docker login -u cvstleee -p %Aylin406#%'
                        }
                            bat "docker build -t cvstleee/tingesofrontend ."
                            bat "docker push cvstleee/tingesofrontend"
                    }                    
                }
            }
        }
    }
}
